name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}

      - name: Add PythonAnywhere to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "ssh.pythonanywhere.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAQHc1w+GUGBVXEAXpcGaY6pVuEltdTSX4V7f8hbc5z1 fplnepal@gmail.com" >> ~/.ssh/known_hosts

      - name: Deploy to PythonAnywhere
        run: |
          ssh fplnepal@ssh.pythonanywhere.com <<EOF
          cd /home/fplnepal/webapp
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          touch /var/www/fplnepal_pythonanywhere_com_wsgi.py
          EOF
