name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}

      - name: Remove old PythonAnywhere host key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "ssh.pythonanywhere.com"

      - name: Add PythonAnywhere to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Deploy to PythonAnywhere
        run: |
          ssh fplnepal@ssh.pythonanywhere.com <<EOF
          cd /home/fplnepal/webapp
          git clean -fd
          git reset --hard HEAD
          git pull origin main
          if [ ! -d "venv" ]; then
              python3 -m venv venv
          fi
          source venv/bin/activate
          pip install --cache-dir ~/.cache/pip -r requirements.txt || true
          touch /var/www/fplnepal_pythonanywhere_com_wsgi.py
          EOF

      - name: Restart PythonAnywhere web app
        run: |
          ssh fplnepal@ssh.pythonanywhere.com "touch /var/www/fplnepal_pythonanywhere_com_wsgi.py"
